display_name: Bingo Web
info: true
build: time crystal build ./src/bingo_web.cr --no-debug
run: ./bingo_web
watch:
  - src/bingo_web/*.cr
  - src/bingo_web/**/*.cr
  - src/bingo_league/**/*.cr
  - src/bingo_rooms/*
  - src/cobingo/*
